#ifndef BATTERY_VALIDATION_H
#define BATTERY_VALIDATION_H

#define TEMP_MIN 0
#define TEMP_MAX 45
#define SOC_MIN 20
#define SOC_MAX 80
#define CHARGE_RATE_MIN 0
#define CHARGE_RATE_MAX 0.8

#define WARNING_TOLERANCE 0.05
#define TEMP_WARNING_TOLERANCE (TEMP_MAX * WARNING_TOLERANCE)
#define SOC_WARNING_TOLERANCE (SOC_MAX * WARNING_TOLERANCE)
#define CHARGE_RATE_WARNING_TOLERANCE (CHARGE_RATE_MAX * WARNING_TOLERANCE);

// Enable/Disable warnings 
#define TEMPERATURE_WARNING 1
#define SOC_WARNING 1
#define CHARGE_RATE_WARNING 1

int batteryIsOk(float temperature, float soc, float chargeRate);

#endif // BATTERY_VALIDATION_H
